repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=2000"]
  - repo: local
    hooks:
      - id: local-mypy
        name: mypy
        entry: "uv run mypy"
        language: python
        types: [python]
        require_serial: true

      - id: local-ruff-check
        name: ruff-check
        entry: "uv run ruff check . --fix"
        language: python
        types: [ python ]
        require_serial: true

      - id: local-ruff-format
        name: ruff-format
        entry: "uv run ruff format ."
        language: python
        types: [ python ]
        require_serial: true
