defaults:
  - _self_
  - dataset: plantseg
  - sam@model.config: sam2.1_hiera_l # choose between: sam2.1_hiera_l sam2.1_hiera_t  sam2.1_hiera_s sam2.1_hiera_b+


model:
  hf_id: facebook/sam2.1-hiera-large # choose between: facebook/sam2.1-hiera-large facebook/sam2.1-hiera-tiny facebook/sam2.1-hiera-small facebook/sam2.1-hiera-base-plus
  threshold: 0.0 # threshold to binarize the logits

root: /storage/ml/
device: cpu

load:
  batch_size: 16
  num_workers: 2

pipeline:
  seed: 42
  k_shots: null # how much sample to draw randomly in the dataset
  min_area: 10 # the minimum area of the segmentation mask to be considered valid in ground truth
  num_points: 5 # number of single click points to segment from
  compute_logits: False # compute logits for the segmentation mask
  use_bounding_box: True # use bounding box in addition to points

visualization:
  show_sam_logits: False # show logits in the visualization
  show_sam_mask: True # show mask in the visualization

logging:
  mlflow_tracking_uri: /storage/ml/mlruns

pixeltable:
  dir_name: null
  run_name: null
  table_name: null
  if_exists: ignore
