label: null # fill out the label column in pixeltable
label_col: null # fill out the label column in pixeltable from another existing column

args:
  _target_: any_gold.image.kpi.KPITask1PatchLevel
  root: /storage/ml/kpi_task1
  split: train
